version: 2

updates:

- package-ecosystem: "docker"
  directory: "/graphviz/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "9:00"

- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "9:00"
